### ISSUE TITLE
Alteração API bla bla bla

### ISSUE THREAD

**Issue by andersonfonsecapeers** [br-openinsurance/areadesenvolvedor#36]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in nulla a nisi commodo tempus. Maecenas ut odio a dui pharetra cursus eu vitae lacus. Phasellus est nibh, iaculis nec viverra sed, dignissim eget libero. Fusce risus mi, faucibus quis lacus nec, molestie maximus ex. Morbi vel vestibulum justo. Etiam sit amet consequat sapien. Donec vestibulum nisl quis quam feugiat, id consequat purus rhoncus. Nam sed vulputate justo. Sed vulputate facilisis augue non egestas.

Pellentesque non tellus vitae massa pharetra blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam elementum odio nulla. Mauris eu ullamcorper sapien, sed gravida augue. Donec luctus purus id commodo vehicula. Praesent sed viverra justo. Donec lacinia mauris ac bibendum pellentesque. Fusce sed orci nec diam porttitor scelerisque. Pellentesque mollis libero eu nulla euismod, non suscipit velit porta. Proin ullamcorper accumsan orci id cursus. Nam vestibulum nulla tristique sem rhoncus rhoncus. Sed nec magna turpis. Quisque non urna aliquam, faucibus lacus non, pellentesque diam. Donec nisl augue, interdum a odio id, efficitur molestie justo. Nulla purus diam, consequat pretium mi in, posuere vulputate dolor. Nunc sollicitudin tristique ipsum in tincidunt.

**Comment by carlosjustino** [comment]
ok
